services:

  symphytum:
    container_name: symphytum
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - CUSTOM_USER=admin
      - PASSWORD=p4ssw0rd
      - LC_ALL=es_ES.UTF-8
      - TITLE=Symphytum
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - "8200:3000"
      - "8300:3001"
    shm_size: "1gb" #optional
    restart: unless-stopped
